import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FaWhatsappSquare } from 'react-icons/fa'
import { AiOutlineMessage } from 'react-icons/ai'
import { useRef, useState } from 'react'

const Home: NextPage = () => {
  const inputCard = useRef()
  const [number, setNumber] = useState<number>()
  const [text, setText] = useState<number>()
  const [done, setDone] = useState<boolean>()

  const maskPhone = () => {
    if (!inputCard.current) return

    //@ts-ignore
    inputCard.current.value = inputCard.current.value
      .replace(/\D/g, '')
      .replace(/(\d{2})(\d)/, '($1) $2')
      .replace(/(\d{5})(\d{4})(\d)/, '$1-$2')
    //@ts-ignore
    setNumber(inputCard.current.value.replace(/\D/g, ''))
  }
  const copy = async () => {
    if (!number) return
    await navigator.clipboard.writeText(number.toString())
    setDone(true)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {done && (
        <div className={styles.divCopy}>
          <span className={styles.copy}>Copiado!</span>
        </div>
      )}
      <main className={styles.main}>
        <section className={styles.secForm}>
          <div className={styles.containerInput}>
            <FaWhatsappSquare color="green" size={50} className={styles.icon} />
            <div className={styles.boxInput}>
              <label htmlFor="number"> Número </label>
              <input
                name="number"
                onChange={maskPhone}
                // @ts-ignore
                ref={inputCard}
                placeholder="(DDD) 9 9999-9999"
              />
            </div>
          </div>
          <div className={styles.containerInput}>
            <AiOutlineMessage color="green" size={50} className={styles.icon} />
            <div className={styles.boxInput}>
              <label htmlFor="msg"> Mensagem </label>
              <textarea
                // @ts-ignore
                onChange={(e) => setText(e.target.value)}
                name="msg"
                placeholder="oieeee"
              />
            </div>
          </div>
          <button onClick={copy} className={styles.button}>
            Gerar link e copiar
          </button>
          <a
            target="_blank"
            href={`https://api.whatsapp.com/send?phone=55${number}&text=${text}`}
            className={styles.linkOpen}
            rel="noreferrer"
          >
            Gerar e abrir link
          </a>
        </section>
      </main>
    </div>
  )
}

export default Home
